# Generated by Django 4.0.10 on 2025-08-13 06:25

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_secret_key', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['name', 'is_active'], name='banks_name_db1c6c_idx'),
        ),
    ]
